TIC_SERIAL = None

FILTER_POSITIONS = {
    1: -57,
    2: -257,
    3: -457,
    4: -657,
}

FILTERWHEEL_STEP_MODE = 8
FILTERWHEEL_CURRENT_LIMIT_MA = 1500
FILTERWHEEL_MAX_SPEED = 4000000
FILTERWHEEL_STARTING_SPEED = 0
FILTERWHEEL_MAX_ACCEL = 40000
FILTERWHEEL_MAX_DECEL = 40000
FILTERWHEEL_POSITION_TOLERANCE = 5
FILTERWHEEL_SETTLE_TIME_S = 0.2
FILTERWHEEL_MOVE_TIMEOUT_S = 10.0

HALL_DIO_BIT = 1
HALL_ACTIVE_STATE = 0

FILTERWHEEL_HOME_ENABLED = True
FILTERWHEEL_HOME_SEARCH_DIRECTION = -1
FILTERWHEEL_HOME_FAST_STEP = 50
FILTERWHEEL_HOME_SLOW_STEP = 1
FILTERWHEEL_HOME_MAX_STEPS = 3000

# Camera power relay control through MCC DIO
CAMERA_POWER_CONTROL_ENABLED = True
CAMERA_POWER_DIO_BIT = 2
CAMERA_POWER_ACTIVE_STATE = 1
CAMERA_POWER_BOOT_WAIT_S = 45.0
CAMERA_POWER_OFF_AT_TEST_END = True


CAMERA_IP = "10.100.10.100"
CAMERA_USER = "root"
REMOTE_CAPTURE_SCRIPT = "/root/scripts/capture_remote.py"
REMOTE_DATA_ROOT = "/root/scripts/data"


TEST_NAME = "freezer_test"
TEST_DURATION_HOURS = 1.0
SWEEP_INTERVAL_SECONDS = 180
MAX_SWEEPS = 25
RETRY_DELAY_SECONDS = 30
MAX_CONSECUTIVE_FAILURES = 3
MINIMUM_FREE_GB = 5.0

# Default exposure if a filter has no specific value
DEFAULT_EXPOSURE_TIME_ABSOLUTE = 20000

# Per-filter exposure settings.
FILTER_EXPOSURE_TIME_ABSOLUTE = {
    1: 3000,
    2: 18000,
    3: 8000,
    4: 11000,
}

LAMP_WARMUP_S = 2.0


try:
    from Config.local_config import *
except ImportError:
    pass