TIC_SERIAL = None

FILTER_POSITIONS = {
    1: -315,
    2: -115,
    3: 85,
    4: 286,
}

FILTERWHEEL_STEP_MODE = 8
FILTERWHEEL_CURRENT_LIMIT_MA = 1500
FILTERWHEEL_MAX_SPEED = 4000000
FILTERWHEEL_STARTING_SPEED = 0
FILTERWHEEL_MAX_ACCEL = 40000
FILTERWHEEL_MAX_DECEL = 40000
FILTERWHEEL_POSITION_TOLERANCE = 5
FILTERWHEEL_SETTLE_TIME_S = 0.2
FILTERWHEEL_MOVE_TIMEOUT_S = 10.0

CAMERA_IP = "10.100.10.100"
CAMERA_USER = "root"
REMOTE_CAPTURE_SCRIPT = "/root/scripts/capture_remote.py"
REMOTE_DATA_ROOT = "/root/scripts/data"

LOCAL_DATA_ROOT = "/home/jcpe/Documents/Projects /FreezerTestSetup/Test_Results"


TEST_NAME = "freezer_test"
TEST_DURATION_HOURS = 0.02
SWEEP_INTERVAL_SECONDS = 15
MAX_SWEEPS = 2
RETRY_DELAY_SECONDS = 30
MAX_CONSECUTIVE_FAILURES = 3
MINIMUM_FREE_GB = 5.0